name: Update Apple Music Playlist

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Update-AM-Playlist
    if: ${{ github.actor != 'qhyBot' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.QHYBOT_GITHUB_TOKEN }}

      - name: Import GPG key for signing
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.QHYBOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update playlist
        uses: qhy040404/am-update-time@v1.0.2
        with:
          playlist: 'https://music.apple.com/cn/playlist/just-my-favorite/pl.u-8aAVZglHWya2xM'
          keyword: 'Last Update: '

      - name: Commit changes
        shell: sh
        run: |
          set -eu

          git add README.md

          if ! git diff --cached --quiet; then
              git commit -S -m "Update playlist"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.QHYBOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
