name: Update wakatime stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "1 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Validate Go
        uses: actions/setup-go@v3

      - name: Clone and run waka-box
        run: |
          git clone https://github.com/YouEclipse/waka-box-go.git
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/

      - name: Commit and push
        run: |
          ./waka
          git config --global user.email "104984534+qhyBot@users.noreply.github.com" && git config --global user.name "qhyBot"
          git diff
          git add README.md && git commit -m ":memo: Update profile" || exit 0
          git pull && git push