name: Update wakatime stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "1 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.QHYBOT_GITHUB_TOKEN }}

      - name: Validate Go
        uses: actions/setup-go@v3

      - name: Clone and run waka-box
        run: |
          git clone https://github.com/YouEclipse/waka-box-go.git
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/

      - name: Import GPG key for signing
        uses: crazy-max/ghaction-import-gpg@v4.4.0
        with:
          gpg_private_key: ${{ secrets.QHYBOT_GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        shell: sh
        run: |
          ./waka

          git add README.md

          if ! git diff --cached --quiet; then
              git commit -m "Update profile"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.QHYBOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}